# Generated by Django 3.2.9 on 2021-12-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='depth',
        ),
    ]
