# Generated by Django 3.2.9 on 2021-12-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_remove_comment_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
