# Generated by Django 3.2.9 on 2021-11-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
